[workspace]
members = [
  "fennel-compile",
  "fennel-mount",
  "fennel-searcher",
  "fennel-src",
  "meka-config",
  "meka-macros",
  "meka-module-manifest",
  "meka-module-manifest-tests",
  "meka-utils",
  "mlua-module-manifest",
  "mlua-searcher",
  "mlua-utils"
]
resolver = "3"

[workspace.package]
edition = "2024"
authors = ["Andy Weidenbaum <atweiden@ioiojo.com>"]
license = "MIT OR Apache-2.0"
keywords = ["fennel", "lua"]
repository = "https://git.sr.ht/~ioiojo/meka"

[workspace.dependencies]
derive_builder = { version = "0.20" }
gpgrv = { version = "0.4" }
ignore = { version = "0.4" }
io-cat = { git = "https://git.sr.ht/~ioiojo/io-cat", rev = "3d03694e8d741c10e9818b7539b78bc85b0bf2b1" }
mlua = { version = "0.10", default-features = false }
once_cell = { version = "1" }
optional-collections = { git = "https://git.sr.ht/~ioiojo/optional-collections", rev = "d9a0720d39b975bd0c117e42e12aba2c1d908a6d" }
paste = { version = "1" }
proc-macro2 = { version = "1" }
quote = { version = "1" }
semver = { version = "1" }
serial_test = { version = "3" }
syn = { version = "2", features = ["full"] }
