[package]
name = "meka-utils"
version = "0.1.0"
edition = "2024"
homepage = "https://git.sr.ht/~ioiojo/meka/tree/master/item/meka-utils"
readme = "README.md"
description = "Utility functions for Meka"
