default: check

# Run cargo check passing mlua features lua54 vendored
check:
  cargo check --features fennel160,mlua-lua54,mlua-vendored

# Run cargo test passing mlua features lua54 vendored
test:
  cargo test --features fennel160,mlua-lua54,mlua-vendored
