[package]
name = "mlua-searcher"
version = "0.1.0"
edition = "2024"
homepage = "https://git.sr.ht/~ioiojo/meka/tree/master/item/mlua-searcher"
readme = "README.md"
description = "Require Lua modules by name"

[features]
# mlua doesn't enable any features by default, so neither do we
default = []
mlua-lua54 = ["mlua/lua54"]
mlua-lua53 = ["mlua/lua53"]
mlua-lua52 = ["mlua/lua52"]
mlua-lua51 = ["mlua/lua51"]
mlua-luajit = ["mlua/luajit"]
mlua-luajit52 = ["mlua/luajit52"]
mlua-luau = ["mlua/luau"]
mlua-luau-jit = ["mlua/luau-jit"]
mlua-luau-vector4 = ["mlua/luau-vector4"]
mlua-vendored = ["mlua/vendored"]

[dependencies]
io-cat = { workspace = true }
mlua = { workspace = true }

[dev-dependencies]
mlua = { workspace = true, default-features = false, features = ["lua54", "vendored"] }
mlua-searcher = { path = ".", default-features = false, features = ["mlua-lua54", "mlua-vendored"] }
